// 多言語対応機能

let currentLanguage = 'ja'; // デフォルトは日本語

// 言語設定を初期化
function initializeLanguage() {
    // ローカルストレージから言語設定を取得
    const savedLang = localStorage.getItem('language');
    if (savedLang) {
        currentLanguage = savedLang;
    }
    
    // 言語を適用
    applyLanguage(currentLanguage);
    
    // 言語切り替えボタンのイベントリスナー
    const langToggle = document.getElementById('langToggle');
    if (langToggle) {
        langToggle.addEventListener('click', toggleLanguage);
    }
}

// 言語を切り替え
function toggleLanguage() {
    currentLanguage = currentLanguage === 'ja' ? 'en' : 'ja';
    localStorage.setItem('language', currentLanguage);
    applyLanguage(currentLanguage);
    
    // プレビューを更新（言語が変わったコメントを反映）
    if (typeof updatePreview === 'function') {
        updatePreview();
    }
}

// 言語を適用
function applyLanguage(lang) {
    // 現在の言語表示を更新
    const currentLangSpan = document.getElementById('currentLang');
    if (currentLangSpan) {
        currentLangSpan.textContent = lang === 'ja' ? '日本語' : 'English';
    }
    
    // すべてのi18n要素を更新
    const elements = document.querySelectorAll('.i18n');
    elements.forEach(element => {
        const text = element.getAttribute(`data-${lang}`);
        if (text) {
            // textContentかinnerHTMLか判定
            if (element.tagName === 'CODE' || element.classList.contains('canvas-placeholder')) {
                element.textContent = text;
            } else if (element.tagName === 'SPAN') {
                element.textContent = text;
            } else {
                element.innerHTML = text;
            }
        }
    });
    
    // ブロックの説明も更新
    updateBlockDescriptions(lang);
    
    // ランタイム情報パネルも更新
    if (typeof updateRuntimeInfo === 'function' && typeof getCurrentRuntime === 'function') {
        updateRuntimeInfo(getCurrentRuntime());
    }
    
    // プレビューも更新（ブロックがない場合の初期メッセージを更新）
    if (typeof updatePreview === 'function') {
        updatePreview();
    }
}

// ブロックの説明を言語に応じて更新
function updateBlockDescriptions(lang) {
    // パレットのブロック
    document.querySelectorAll('.blocks-container .block').forEach(block => {
        const blockType = block.dataset.blockType;
        if (blockType && blockDefinitions[blockType]) {
            const def = blockDefinitions[blockType];
            const descElement = block.querySelector('.block-description');
            if (descElement) {
                if (lang === 'en' && def.description_en) {
                    descElement.textContent = def.description_en;
                } else {
                    descElement.textContent = def.description;
                }
            }
        }
    });
    
    // キャンバスのプレースホルダーも更新
    const placeholder = document.querySelector('.canvas-placeholder');
    if (placeholder) {
        const text = lang === 'ja' 
            ? 'ブロックをここにドラッグしてContainerfileを作成しよう！'
            : 'Drag blocks here to create your Containerfile!';
        placeholder.textContent = text;
    }
}

// 現在の言語を取得
function getCurrentLanguage() {
    return currentLanguage;
}

// 翻訳テキストを取得
function t(key, lang = null) {
    const l = lang || currentLanguage;
    const translations = {
        ja: {
            'generated_by': 'Generated by Container File Builder',
            'created_at': '作成日時:',
            'empty_preview': '# ここにContainerfileが表示されます\n# 左側のブロックをキャンバスに追加してください',
            'copy_success': 'コピーしました！',
            'download_success': 'ダウンロードしました！',
            'clear_confirm': 'すべてのブロックを削除しますか？',
            'delete_confirm': 'このブロックを削除しますか？',
            'validation_perfect': '完璧です！',
            'validation_no_errors': 'Containerfileに問題は見つかりませんでした。',
            'required_field': '必須項目を入力してください',
            'modal_edit': 'ブロックを編集',
            'modal_cancel': 'キャンセル',
            'modal_save': '保存'
        },
        en: {
            'generated_by': 'Generated by Container File Builder',
            'created_at': 'Created at:',
            'empty_preview': '# Your Containerfile will be displayed here\n# Add blocks from the left panel to the canvas',
            'copy_success': 'Copied!',
            'download_success': 'Downloaded!',
            'clear_confirm': 'Are you sure you want to delete all blocks?',
            'delete_confirm': 'Are you sure you want to delete this block?',
            'validation_perfect': 'Perfect!',
            'validation_no_errors': 'No issues found in the Containerfile.',
            'required_field': 'Please fill in all required fields',
            'modal_edit': 'Edit Block',
            'modal_cancel': 'Cancel',
            'modal_save': 'Save'
        }
    };
    
    return translations[l][key] || key;
}

